### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by drusepth** [heroku/barnes#25]
Is this gem supported in Rails 6? I'm starting the upgrade process for an app from 5.2 to 6.0 and don't see anything in the README about 6+, so I thought I'd ask before just removing the gem. Thanks!

**Comment by schneems** [comment]
Yes, it works with Rails 6. Can you send me a PR updating the README?
-- 
Richard Schneeman
https://www.schneems.com

**Comment by prathamesh-sonpatki** [comment]
This issue can be closed as #26 is merged

**Comment by stevenharman** [comment]
Closed by #26
