### ISSUE TITLE
Add some documentation for use.

### ISSUE THREAD

**Issue by apg** [heroku/barnes#6]
This is not currently documented, and as a result it's not clear how to set this up in a ruby app. 

For rails, I think it's a matter of using the Railtie. For any other ruby app, it's a bit different, which isn't documented.

**Comment by michellep** [comment]
I have a Ruby specific Dev Center doc created (draft): https://devcenter.heroku.com/articles/language-runtime-metrics-ruby  It still needs specific installation instructions and the finalized plot list and screenshots.

**Comment by freeformz** [comment]
@apg @schneems This was closed by #9, correct?

**Comment by apg** [comment]
Yes.
